name: "Build Domain"
description: "Build packages and publish artifacts via SFP Server"
author: "flxbl-io"

branding:
  icon: "package"
  color: "blue"

inputs:
  sfp-server-url:
    description: "URL to the SFP Server instance (e.g., https://your-org.flxbl.io)"
    required: true
  sfp-server-token:
    description: "Token for SFP Server authentication"
    required: true
  release-config:
    description: "Path to release config file (required for build and release candidate)"
    required: true
  repository:
    description: "Repository name (format: owner/repo)"
    required: false
    default: ${{ github.repository }}
  branch:
    description: "Branch name for build identification"
    required: false
    default: ${{ github.ref_name }}
  build-number:
    description: "Build number for source packages"
    required: false
    default: ${{ github.run_id }}
  release-name:
    description: "Name for the release candidate"
    required: false
    default: ""
  diff-check:
    description: "Only build packages that have changed"
    required: false
    default: "true"
  npm-scope:
    description: "NPM scope for publishing (without @)"
    required: false
    default: ${{ github.repository_owner }}
  npm:
    description: "Publish to external npm registry (when false, uses internal-only)"
    required: false
    default: "false"
  git-tag:
    description: "Create git tags for published artifacts"
    required: false
    default: "true"
  push-git-tag:
    description: "Push git tags to remote repository"
    required: false
    default: "true"
  serialize:
    description: "Serialize builds for this domain (prevents concurrent builds)"
    required: false
    default: "true"
  serialize-timeout:
    description: "Max seconds to wait for serialization lock"
    required: false
    default: "900"
  serialize-lease:
    description: "Duration in seconds to hold the serialization lock"
    required: false
    default: "1800"

outputs:
  has-artifacts:
    description: "Whether artifacts were produced (true/false)"
  artifact-count:
    description: "Number of artifacts produced"
  artifacts-dir:
    description: "Path to artifacts directory"

runs:
  using: "node20"
  main: "dist/index.js"
  post: "dist/cleanup.js"
  post-if: "always()"
